### PR TITLE
Rails 7.0 support

### PR DESCRIPTION
**Pull request by misdoro**
Add rails 7 to the tests matrix, copy-paste rails 6.0 compatibility layer as rails 7.

### CODE REVIEW

**Comment by misdoro** [comment]
:thinking: Weird, it did not trigger any github actions.

**Comment by misdoro** [comment]
It doesn't really work yet, and it should be draft until the CI is fixed.

**Comment by olleolleolle** [comment]
@misdoro i squashed and merged the other PR, thanks for the fix.

**Comment by misdoro** [comment]
Thanks @olleolleolle , the tests are passing now even for rails 7 :tada: 

No guarantees that the code is optimal or whatsoever, I am far from being an expert in active record :)

**Comment by nickcampbell18** [comment]
I can't comment on the performance as such, but I've incorporated this fork into one of my applications and it seems to work in Rails `7.0.0` as well as on Rails `6.1.4` 🎉

**Comment by olleolleolle** [comment]
Let's get this merged!

**Pull request merged**
