### PR TITLE
Add v0.11.2, fix readme formatting

### PR DESCRIPTION
**Pull request by olleolleolle**
This PR is about getting a new release out.

### CODE REVIEW

**Review by jesjos — APPROVED** [review]

**Comment by olleolleolle** [comment]
@jesjos It took me a little time to get the GPG set up and have Verified on all my commits from this laptop. Thanks!

**Comment by jgraichen** [comment]
It seems the release to rubygems.org is still missing: https://rubygems.org/gems/active_record_upsert/versions. Is there an issue we can help with?

**Comment by olleolleolle** [comment]
Seems the CI automation for releasing new upon marking a release in GitHub Releases had failed.

I made the release now, using the command-line tool `bundle exec release` (and then using Safari to authenticate with the macOS Touch ID).

**Comment by jgraichen** [comment]
@olleolleolle Thank you!

Should that automation be public? I didn't find anything in the GitHub Action workflows.

**Comment by olleolleolle** [comment]
@jgraichen Ah, this was so long ago, I mixed it up with some other project. Sorry, you're right, no configured CI automation seems to be in place.

**Pull request merged**
