### PR TITLE
Rails 5.2 compatibility

### PR DESCRIPTION
**Pull request by benedikt**
Rails 5.2.0.rc1 changes a bunch of ActiveRecord internals. As a result, this gem wouldn't work anymore.
This pull request adjusts the implementation to work with Rails 5.2. While the code got a bit simpler, it isn't compatible with earlier Rails versions anymore.

I'm starting this pull request to provide a working implementation for Rails 5.2, and to start a discussion about how to ensure backwards compatibility.

What are your thoughts on this?

Cheers,

Benedikt

### CODE REVIEW

**Comment by olleolleolle** [comment]
Hi, and thanks for taking the long trek!

Getting to a working 5.2 implementation is the golden step 1, and then to get this mergeable, we will need to have a few unsightly "if" statements etc in the code to support more than one version.

**Comment by jesjos** [comment]
Maybe we should separate the implementations needed for the different versions of AR into separate modules and then concentrate all of the needed if:s into `lib/active_record_upsert/active_record.rb`?

**Comment by olleolleolle** [comment]
(Appreciating the work you're doing here, it gets very shiny!)

**Comment by benedikt** [comment]
I just added a small compatibility layer that restores functionality for Rails 5.0-5.1.

Let me know what you think!

**Comment by olleolleolle** [comment]
I'm for it!

**Comment by olleolleolle** [comment]
I looked around, and the gemspec already has `< 6` and so on, so I think we are ready to go with this change!

**Pull request merged**
