### PR TITLE
support arel 9.0

### PR DESCRIPTION
**Pull request by timoschilling**

### CODE REVIEW

**Comment by olleolleolle** [comment]
Thanks for noting the update neeeed. The tests pass, that’s great.

**Comment by olleolleolle** [comment]
But the version specifier in this PR is about being _less than_ 10, which makes this work on arel 9 I guess?

**Comment by timoschilling** [comment]
sorry wrong PR name, 9.0 is the newest version

**Comment by timoschilling** [comment]
but i will close this PR, it didn't make sense, while rails pins the arel version

**Pull request closed without merging**
